### ISSUE TITLE
"configure" command not found

### ISSUE THREAD

**Issue by benhepburnn** [adonisjs-community/create-adonis-ts-app#59]
## Bug

The issue occurs at the "Configure installed packages" step.

I'm using an M2 Pro Macbook, running macOs 13.2.1.

```
┌ Configure installed packages
│  CREATE: config/app.ts
│  CREATE: .env,.env.example
│  SKIP:   env.ts
│  CREATE: config/bodyparser.ts
│  CREATE: config/drive.ts
│  CREATE: config/cors.ts
│  CREATE: config/hash.ts
│  CREATE: contracts/events.ts
│  CREATE: contracts/drive.ts
│  CREATE: contracts/hash.ts
│  CREATE: contracts/env.ts
│  UPDATE: tsconfig.json 
│  UPDATE: .adonisrc.json 
│  UPDATE: .adonisrc.json 
│  UPDATE: tsconfig.json 
│  UPDATE: .adonisrc.json 
│  UPDATE: .adonisrc.json 
[ error ]  "configure" command not found
│  [ error ]  Command failed with exit code 1: node ace configure tests
│      at makeError (/Users/benhepburn/Library/pnpm/store/v3/tmp/dlx-37071/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
│      at handlePromise (/Users/benhepburn/Library/pnpm/store/v3/tmp/dlx-37071/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
│      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
│      at async task (/Users/benhepburn/Library/pnpm/store/v3/tmp/dlx-37071/node_modules/.pnpm/create-adonis-ts-app@4.2.4/node_modules/create-adonis-ts-app/build/Tasks/ConfigureTests/index.js:24:9)
│      at async Object.callback (/Users/benhepburn/Library/pnpm/store/v3/tmp/dlx-37071/node_modules/.pnpm/create-adonis-ts-app@4.2.4/node_modules/create-adonis-ts-app/build/index.js:95:17)
│      at async TaskManager.runTask (/Users/benhepburn/Library/pnpm/store/v3/tmp/dlx-37071/node_modules/.pnpm/@poppinss+cliui@3.0.5/node_modules/@poppinss/cliui/build/src/Task/Manager.js:99:13)
│      at async Object.complete (/Users/benhepburn/Library/pnpm/store/v3/tmp/dlx-37071/node_modules/.pnpm/@poppinss+cliui@3.0.5/node_modules/@poppinss/cliui/build/src/Task/Manager.js:82:13)
│      at async Object.callback (/Users/benhepburn/Library/pnpm/store/v3/tmp/dlx-37071/node_modules/.pnpm/create-adonis-ts-app@4.2.4/node_modules/create-adonis-ts-app/build/index.js:97:13)
│      at async TaskManager.runTask (/Users/benhepburn/Library/pnpm/store/v3/tmp/dlx-37071/node_modules/.pnpm/@poppinss+cliui@3.0.5/node_modules/@poppinss/cliui/build/src/Task/Manager.js:99:13)
│      at async Object.complete (/Users/benhepburn/Library/pnpm/store/v3/tmp/dlx-37071/node_modules/.pnpm/@poppinss+cliui@3.0.5/node_modules/@poppinss/cliui/build/src/Task/Manager.js:82:13)
└ failed (247 ms)

[ error ]  Unable to create project. Cleaning up
```

## Package version
Latest at 11th Sept 2023

## Node.js and npm version
Problem occurs in:
- Node v20.6.1, npm v9.8.1
- Node v16.20.1, npm v8.19.4
- Problem occurs with both npm and pnpm

## Sample Code (to reproduce the issue)
```bash
pnpm create adonis-ts-app myy-api
```

**Comment by benhepburnn** [comment]
This was fixed after I restarted my computer (I think)
